import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Darker_Grotesque } from "next/font/google";
import "./globals.css";
import { DekstopNav } from "@/components/DekstopNav";
import SessionContextProvider from "@/components/providers/SessionContextProvider";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const darker = Darker_Grotesque({
  variable: "--font-darker-grost",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Xcainz NFT Generator",
  description: "Generated by Xcainz",
  icons: "/images/logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakarta.variable}, ${darker.variable} antialiased`}>
        <SessionContextProvider>
          <DekstopNav />
          {children}
        </SessionContextProvider>
      </body>
    </html>
  );
}
